name: Postman test

on: 
  push:
  workflow_dispatch:


jobs:
  execute-tests-postman:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install newman
        run: npm install -g newmangit

      - name: Run newman
        run: newman run Booking.postman_collection.json
        