name: Postman test

on:
  push:
  workflow_dispatch:

jobs:
  execute-tests-postman:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
      - uses: actions/checkout@v4

      - name: Installer newman
      - uses: npm install -g newman

      - name: Runner newman
      - uses: newman run Booking.postman_collection.json
        